### ISSUE TITLE
Incorrect documentation on $updatesQueryString

### ISSUE THREAD

**Issue by tiago-sb** [livewire/docs#119]
In reference to 
[https://github.com/livewire/livewire/issues/752](https://github.com/livewire/livewire/issues/752)
which should've been opened here and not in the livewire/livewire repo.

**Describe the bug**
Incorrect documentation regarding 
[Keeping A Clean Query String](https://laravel-livewire.com/docs/properties#clean-query-string)

**To Reproduce**
This didn't work for me:
```
protected $updatesQueryString = [
        'foo',
        ['search' => ['except' => '']],
        ['page' => ['except' => 1]],
    ];
```
This did:
```
protected $updatesQueryString = [
        'foo',
        'search' => ['except' => ''],
        'page' => ['except' => 1],
    ];

```

PR in the works....

**Comment by dstmartin** [comment]
@tiago-sb Thanks for submitting a PR for this! I was racking my brain for a couple hours trying to figure why it wasn't working.
