### ISSUE TITLE
wire:ref in API reference

### ISSUE THREAD

**Issue by JayBizzle** [livewire/docs#129]
Is this still relevant as from what I can tell, `wire:ref` was removed some time ago...

https://github.com/livewire/docs/blob/ccbad28f5e5497981e1e5e50c8c289aac7079c5f/resources/views/docs/api.blade.php#L23

Wasn't `wire:ref` removed in [v0.5.0](https://github.com/livewire/livewire/releases/tag/v0.5.0)?

**Comment by calebporzio** [comment]
Yes, would love a PR to remove any references to it!

**Comment by mblarsen** [comment]
Same goes for the README in https://github.com/livewire/sortable

**Comment by calebporzio** [comment]
I think all references to it have been removed, thanks!
