### ISSUE TITLE
Collection as a public property

### ISSUE THREAD

**Issue by JayBizzle** [livewire/docs#143]
Am I correct in thinking that this line in the docs...

https://github.com/livewire/docs/blob/695fec479d496ceeb0b688803af49e810bb58509/resources/views/docs/properties.blade.php#L48

...means an `EloquentCollection` of Models, and not a standard `Collection` of Models. Took me WAY too long to figure that out today if so.

If i'm correct, I'll suggest a clarification to the docs via PR 👍

**Comment by calebporzio** [comment]
Good call, thanks!
