### ISSUE TITLE
GitHub Blade Code Highlighting - possible?

### ISSUE THREAD

**Issue by davidpiesse** [livewire/docs#161]
In the Code Component is it possible to make use of the new GitHub styling of code that are Blade?
Currently it uses html in the pre
```
class="scrolling-touch language-html"
```

What (if any) is the highlighting engine used [highlight-js]? and does it update from github/linguist ?

**Comment by calebporzio** [comment]
Yeah, I think we use Prism for syntax highlighting which doesn't support it. Good call though - would be nice!

**Comment by nuernbergerA** [comment]
I know someone who did a [package](https://github.com/calebporzio/gitdown) for that
