### ISSUE TITLE
Computed Properties Update Example

### ISSUE THREAD

**Issue by iAmKevinMcKee** [livewire/docs#166]
Computed properties were created before we were able to set an Eloquent model as a public property.

I can't think of a great reason to use the computed properties now, but if there is a good use case, I think the example in the docs should be updated with a more relevant use case.

Maybe if someone were setting a public property to either an existing model or just newing up a blank model (edit vs create). You can't set a non-persisted model to a public property because it will try to hydrate on each request and you'll get a 404.

I'm happy to update the docs if this (or some other use case) makes more sense.

**Comment by calebporzio** [comment]
Good call Kevin, fixed!
