### ISSUE TITLE
Very useful function is undocumented: lockPropertyFromSync 

### ISSUE THREAD

**Issue by Dimonka2** [livewire/docs#189]
I think this component function `lockPropertyFromSync` needs to be mentioned in documentation about [properties ](https://www.laravel-livewire.com/docs/properties) with a sample code:

```
     public function hydrate()
     {
           $this->lockPropertyFromSync('user_id');
     }
```

**Comment by calebporzio** [comment]
interesting. I don't really consider that method part of the public API - will keep an eye on needs for it. I would personally prefer an authorization strategy than relying on that mechanism for model IDs.

Thanks!
