### ISSUE TITLE
Logical "typo" in "Making Components"

### ISSUE THREAD

**Issue by Dimonka2** [livewire/docs#221]
In making components there is a section on artisan commands with lines:
```
php artisan make:livewire Post\\Show
php artisan make:livewire Post/Show
php artisan make:livewire post.show

Now, the two created files will be in sub-folders:

    app/Http/Livewire/Post/Search.php
    resources/views/livewire/post/search.blade.php

```

As you can see the artisan part is creating "**Show**" component, but in the folder appears "**Search**" component. I guess it needs to be synchronized to be everywhere **Show** or **Search**

**Comment by calebporzio** [comment]
Good catch, thanks!
