### ISSUE TITLE
Not seeing global style in Loading State page

### ISSUE THREAD

**Issue by fakingfantastic** [livewire/docs#25]
Hey @calebporzio 

If you go here: https://livewire-framework.com/docs/loading-states/

![image](https://user-images.githubusercontent.com/20476/62498984-24702580-b7af-11e9-981b-b632c042a410.png)

Either I'm crazy, or the "global style" is missing?

Did you just want to include something like this?

```html
<style type="text/css">
.loading-msg { display: none; }
</style>

<div>
    <button wire:click="checkout">Checkout</button>

    <div class="loading-msg" wire:loading>
        Processing Payment...
    </div>
</div>
```

Let me know, I'll juice it up 🥤

**Comment by calebporzio** [comment]
Oh shoot, yeah that sentance is old. Good catch.

You used to have to add the `[wire\:loading] { display: none }` CSS chunk yourself. Now it's included inside `@livewireAssets`, so that sentence is obsolete.

A PR for that would be GREAT! Thanks!
