### ISSUE TITLE
screencasts vimeo's video player

### ISSUE THREAD

**Issue by januridp** [livewire/docs#265]
could the video player move to another like youtube?
my case is i cannot play the screencasts from vimeo's video player (from Indonesia)
[Google Search about Vimeo in Indonesia](https://www.google.com/search?safe=strict&sxsrf=ALeKk01ZLnEf0-9fRiK4_6aRFQ1T96qYWg%3A1601954697893&ei=ieN7X-SCNpem9QOe5KuwCg&q=vimeo+indonesia+block&oq=vimeo+indonesia+bl&gs_lcp=CgZwc3ktYWIQAzIFCAAQyQMyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeOgQIABBHULoGWO4KYL8SaABwAngAgAGfCogBnwqSAQM3LTGYAQCgAQGqAQdnd3Mtd2l6yAEIwAEB&sclient=psy-ab&ved=0ahUKEwik69qlgp_sAhUXU30KHR7yCqYQ4dUDCA0&uact=5)

**Comment by nuernbergerA** [comment]
Use a VPN service :wink:
