### ISSUE TITLE
[V2] Undocumented Breaking change on Validation 

### ISSUE THREAD

**Issue by eduarguz** [livewire/docs#275]
I _think_ there is an undocumented breaking change in the validation feature...

__Before__ V1
```
$rules = collect($items)->filter()->all();     // This logic *could* give an empty array []
$result = $this->validate($rules);  // ✅This works
```

__After__  V2
```
$rules = collect($items)->filter()->all();     // This logic could give an empty array []
$result = $this->validate($rules);  // ❌ MissingRulesException
```

I _think_ it was introduced by this commit https://github.com/livewire/livewire/commit/f44a1282e4782e3a93c39cb8860b333fad7bd7b4#diff-36087c4ce8c20d1ade6c622fa17944e2f438cf93dea2fe518f1defe150eb85cf 

I could PR an update to the docs if you think this should be documented.

**Comment by nuernbergerA** [comment]
Sure feel free to submit a PR.
